# This is a basic workflow to help you get started with Actions

name: Deploy API Doc

env:
  OPENAPI_FILENAME: api-with-examples.yaml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - $OPENAPI_FILENAME
  pull_request:
    branches: [ "main" ]
    paths:
      - $OPENAPI_FILENAME

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Generate api doc file
        run: npx redoc-cli build petstore.yaml --output=docs/index.html
